# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homekit:
  - name: HASS Bridge 2
    filter:
      include_entities:
        - switch.basit_switch

    entity_config:
      switch.basit_switch:
        name: Airco
        type: sprinkler
        linked_timer: timer.hello

input_boolean:
  basit_toggle:
    name: "Basit Switch"
    icon: "mdi:power"

switch:
  - platform: template
    switches:
      basit_switch:
        friendly_name: "Basit Switch"
        value_template: "{{ is_state('input_boolean.basit_toggle', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          data:
            entity_id: input_boolean.basit_toggle
        turn_off:
          service: input_boolean.turn_off
          data:
            entity_id: input_boolean.basit_toggle